# .github/workflows/release.yml
name: Release
on:
  push:
    branches: [ "master" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Check repo context
        run: |
          echo "Repo owner: ${{ github.repository_owner }}"
          echo "Repo name: ${{ github.event.repository.name }}"
        
      - name: Generate Release Notes
        id: release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commits = await github.rest.repos.listCommits({
              owner: '${{ github.repository_owner }}',
              repo: '${{ github.event.repository.name }}',
              per_page: 100
            });

            echo (commits.data.map(commit => `- ${commit.commit.message}`).join('\n'));
            
            const changes = commits.data.map(commit => {
              return `- ${commit.commit.message}`;
            }).join('\n');
            
            const version = require('./package.json').version;
            
            await github.rest.repos.createRelease({
              owner: '${{ github.repository_owner }}', 
              repo: '${{ github.event.repository.name }}',
              tag_name: `v${version}`,
              name: `Release v${version}`,
              body: changes,
              draft: false,
              prerelease: false
            });

      - name: Bump version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version patch -m "Bump version to %s [skip ci]"
          git push
          git push --tags